[Feature] dot in /usr/local/bin (#113)
* Fixed help for dot command

* Added installation of dot command in /usr/local/bin

* Added ::is_windows and improved ::is_bsd

* Added compatibility for non interactive shells

* Disable shellcheck SC2128 in the script level

* Try to locate DOTFILES_PATH in the default directory

Co-authored-by: Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -1,7 +1,27 @@
 #!/usr/bin/env bash
-#shellcheck disable=2016
+#shellcheck disable=SC2128,SC2016
 
 set -o pipefail
+
+# In Linux we can do this with readlink -f but will fail in macOS and BSD OS
+if [[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" || ! -d "${SLOTH_PATH:-${DOTLY_PATH:-}}" ]]; then
+  dot_path="$BASH_SOURCE"
+  until [[ ! -L $dot_path ]]; do
+    dot_path="$(readlink "$dot_path")"
+  done
+  SLOTH_PATH="$(dirname "$(dirname "$dot_path")")"
+  DOTLY_PATH="$SLOTH_PATH"
+
+  if [[ ! -d "$SLOTH_PATH" || ! -x "${SLOTH_PATH}/bin/dot" ]]; then
+    echo "Error: Could not find the SLOTH source code."
+    exit 1
+  fi
+
+  if [[ -z "${DOTFILES_PATH:-}" && -d "${HOME}/.dotfiles/scripts" ]]; then
+    DOTFILES_PATH="$HOME/.dotfiles"
+  fi
+  export SLOTH_PATH DOTLY_PATH DOTFILES_PATH
+fi
 
 #shellcheck disable=SC1091
 . "${SLOTH_PATH:-${DOTLY_PATH:-}}/scripts/core/src/_main.sh"
@@ -24,8 +44,8 @@ SLOTH_SCRIPT_BASE_NAME="sloth"
 ##?    dot
 ##?
 ##? Arguments:
-##?    context  Is the subfolder in "\${DOTFILES_PATH}/scripts/" or "\${DOTLY_PATH:-\${SLOTH_PATH:-${DOTLY_PATH:-}}}/scripts"
-##?    script   Is the script in "\${DOTFILE${SLOTH_PATH:-S_PATH}/scr}ipts/<context>" or "\${DOTLY_PATH:-\${SLOTH_PATH:-${DOTLY_PATH:-}}}/scripts/<conte${SLOTH_PATH:-xt>"
+##?    context  Is the subfolder in "\${DOTFILES_PATH}/scripts/" or "\${SLOTH_PATH:-\${DOTLY_PATH:-}}/scripts"
+##?    script   Is the script in "\${DOTFILES_PATH}/scripts/<context>" or "\${SLOTH_PATH:-\${DOTLY_PATH:-}}/scripts/<context>"
 ##?
 #}#? Options:
 ##?    -h --help     Gives help to the user
@@ -42,8 +62,8 @@ fi
 
 # This script version
 if [[ "$1" == "-v" || "$1" == "--version" ]]; then
-  SCRIPT_VERSION="$(dot::parse_script_version "$0")"
-  SCRIPT_NAME="$(basename "$0")"
+  SCRIPT_VERSION="$(dot::parse_script_version "$BASH_SOURCE")"
+  SCRIPT_NAME="$(basename "$BASH_SOURCE")"
   if [[ -n "${SCRIPT_VERSION}" ]]; then
     output::write "${SCRIPT_NAME}"
     output::write "\t\`v${SCRIPT_VERSION}\`"
