Added a warning when .Sloth is not installed

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -20,6 +20,7 @@ if [[ -z "${SLOTH_PATH:-${DOTLY_PATH:-}}" || ! -d "${SLOTH_PATH:-${DOTLY_PATH:-}
   if [[ -z "${DOTFILES_PATH:-}" && -d "${HOME}/.dotfiles/scripts" ]]; then
     DOTFILES_PATH="$HOME/.dotfiles"
   fi
+  unset dot_path
   export SLOTH_PATH DOTLY_PATH DOTFILES_PATH
 fi
 
@@ -47,17 +48,17 @@ SLOTH_SCRIPT_BASE_NAME="sloth"
 ##?    context  Is the subfolder in "\${DOTFILES_PATH}/scripts/" or "\${SLOTH_PATH:-\${DOTLY_PATH:-}}/scripts"
 ##?    script   Is the script in "\${DOTFILES_PATH}/scripts/<context>" or "\${SLOTH_PATH:-\${DOTLY_PATH:-}}/scripts/<context>"
 ##?
-#}#? Options:
+##? Options:
 ##?    -h --help     Gives help to the user
 ##?    -v --version  Show the dot command version
 ##?
 ##?    self-update
 ##?
-##? SCRIPT_VERSION 2.0.0
+##? SCRIPT_VERSION 2.1.0
 
 # This script help
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-  docs::parse "$@"
+  grep "^##?" "$BASH_SOURCE" | cut -c 5-
 fi
 
 # This script version
@@ -72,6 +73,12 @@ if [[ "$1" == "-v" || "$1" == "--version" ]]; then
     output::error "\t no version provided"
   fi
   exit
+fi
+
+if ! git::is_in_repo -C "${SLOTH_PATH:-${DOTLY_PATH:-}}"; then
+  output::error "Error: .Sloth needs to execute \`dot core install --ignore-symlinks\` previously to be used."
+  output::answer "This will install some tools in your system and also init current .Sloth folder as repository"
+  exit 1
 fi
 
 # Self-update (Why not in dot directly?)
