Changed feedback to the user after applying symlinks

diff --git a/scripts/core/install b/scripts/core/install
--- a/scripts/core/install
+++ b/scripts/core/install
@@ -63,7 +63,12 @@ else
   $bk && output::yesno "Do you want to be asked for every file" || symlinks_args=(--backup)
   ! $bk && symlinks_args=(--ignore-backup)
 fi
-"${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" symlinks apply "${symlinks_args[@]}" --continue-on-error --after-core | log::file "Applying symlinks"
+"${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" symlinks apply "${symlinks_args[@]}" --continue-on-error --after-core 2>&1 | log::file "Applying symlinks"
+if $?; then
+  output::error "All symlinks were applied with errors. Use \`dot self debug\` to see what's wrong"
+else
+  output::solution "Symlinks applied"
+fi
 touch "$HOME/.z"
 unset symlinks_args bk
 
