Fixed sudo

diff --git a/scripts/core/install b/scripts/core/install
--- a/scripts/core/install
+++ b/scripts/core/install
@@ -8,6 +8,22 @@ dot::load_library "install.sh"
 dot::load_library "git_extended.sh"
 dot::load_library "sloth_update.sh"
 
+start_sudo() {
+  sudo -n -v &> /dev/null && return 0
+  sudo -v -B
+  if sudo -n -v &> /dev/null && [[ -z "${SUDO_PID:-}" ]]; then
+    ( while true; do sudo -v; sleep 30; done; ) &
+    SUDO_PID="$!"
+    trap stop_sudo SIGINT SIGTERM
+  fi
+}
+
+stop_sudo() {
+  kill "$SUDO_PID" &>/dev/null
+  trap - SIGINT SIGTERM
+  sudo -k
+}
+
 ##? Install dotly and setup dotfiles. By default use a interactive backup (backups are not done for core symlinks).
 ##?
 ##? Usage:
@@ -83,24 +99,23 @@ if
 then
   SETUP_ZSH_AND_BASH_IN_SHELLS=false
   if
-    output::yesno "Do you want to setup more modern \`zsh\` & \`bash\` as valid shells in \`/etc/shells\` (require elevation)" &&
-      sudo -v -B
+    output::yesno "Do you want to setup more modern \`zsh\` & \`bash\` as valid shells in \`/etc/shells\` (require elevation)"
   then
-    {
+    start_sudo
+    
+    sudo -n -v && SETUP_ZSH_AND_BASH_IN_SHELLS=true
 
-      sudo -v -B && SETUP_ZSH_AND_BASH_IN_SHELLS=true
-
-    } || output::error "It can not be done without elevation, aborting this options (should be done later manually)" && SETUP_ZSH_AND_BASH_IN_SHELLS=false
+    ! sudo -n -v &> /dev/null && output::error "It can not be done without elevation, aborting this options (should be done later manually)" && SETUP_ZSH_AND_BASH_IN_SHELLS=false
   fi
 
 # We need to cache sudo to avoid asking for password later and every time
 elif
   [[ "${DOTLY_ENV:-PROD}" != "CI" ]] &&
     platform::is_macos &&
-    [[ -n "${SETUP_ZSH_AND_BASH_IN_SHELLS:-}" ]] &&
-    ! sudo -v -B
+    [[ -n "${SETUP_ZSH_AND_BASH_IN_SHELLS:-}" ]]
 then
-  output::error "It can not be done without elevation, aborting this options (should be done later manually)"
+  start_sudo
+  ! sudo -n -v &> /dev/null && output::error "It can not be done without elevation, aborting this options (should be done later manually)"
   SETUP_ZSH_AND_BASH_IN_SHELLS=false
 fi
 export SETUP_ZSH_AND_BASH_IN_SHELLS
@@ -134,7 +149,7 @@ if [[ -z "${SETUP_ZSH_AS_DEFAULT_SHELL:-}" ]]; then
   then
     output::yesno "Do you want to setup the zsh \`$zsh_shell_path\` as default shell" && SETUP_ZSH_AS_DEFAULT_SHELL=true
     output::answer "This will need a sudo authentication to add it to \`/etc/shells\` file"
-    if ! sudo -v -B; then
+    if ! sudo -n -v &> /dev/null; then
       output::error "Without sudo authentication this can not be done. You should do this later manually"
       SETUP_ZSH_AS_DEFAULT_SHELL=false
     fi
@@ -146,7 +161,7 @@ else
       [[ ! -x "$zsh_shell_path" ]] ||
       [[ ! -f "/etc/shells" ]] ||
       grep -q "^${zsh_shell_path}$" "/etc/shells" ||
-      ! sudo -v -B
+      ! sudo -n -v &> /dev/null
   then
     output::answer "\`SETUP_ZSH_AS_DEFAULT_SHELL\` should be aborted because it can not be done or is already the default shell or fail with the password."
     SETUP_ZSH_AS_DEFAULT_SHELL=false
@@ -154,6 +169,10 @@ else
 fi
 export SETUP_ZSH_AS_DEFAULT_SHELL
 #### End of prompt user all the staff we want to know ####
+
+if ! sudo -n -v &> /dev/null; then
+  start_sudo
+fi
 
 export ZIM_HOME="${SLOTH_PATH:-${DOTLY_PATH:-}}/modules/zimfw"
 export PATH="$HOME/.cargo/bin:$PATH"
@@ -206,7 +225,7 @@ unset SYMLINKS_ARGS bk
 # ZSH as default shell if we are using zsh
 zsh_shell_path="$(command -v zsh || true)"
 output::answer "Trying to setup zsh as the default shell"
-if $SETUP_ZSH_AS_DEFAULT_SHELL && sudo -v -B; then
+if $SETUP_ZSH_AS_DEFAULT_SHELL && sudo -n -v &> /dev/null; then
   sudo bash -c "echo '$zsh_shell_path' | tee -a /etc/shells" &> /dev/null
 
   {
