Added --without-link optional argument

diff --git a/scripts/core/install b/scripts/core/install
--- a/scripts/core/install
+++ b/scripts/core/install
@@ -37,7 +37,7 @@ has_sudo() {
 ##? Install dotly and setup dotfiles. By default use a interactive backup (backups are not done for core symlinks).
 ##?
 ##? Usage:
-##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-restoration]
+##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-restoration] [--without-link]
 ##?
 ##? Options:
 ##?    -h --help                Prints this help
@@ -46,6 +46,7 @@ has_sudo() {
 ##?    -i --interactive-backup  Interactive backup of user symlinks asking for every existing symlink before to be applied (default)
 ##?    --ignore-symlinks        Ignore apply symlinks. Useful for very custom installations
 ##?    --ignore-restoration     Ignore user restoration scripts
+##?    --without-link           Ignore link dot command in /usr/local/bin
 ##?
 ##? SCRIPT_VERSION "3.0.0"
 if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docpars"; then
@@ -58,6 +59,7 @@ else
   ignore_backup=false
   ignore_symlinks=false
   ignore_restoration=false
+  without_link=false
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --version | -v)
@@ -90,6 +92,10 @@ else
         ;;
       --ignore-restoration)
         ignore_restoration=true
+        shift
+        ;;
+      --without-link)
+        without_link=true
         shift
         ;;
       *)
@@ -315,25 +321,27 @@ if [[ "${DOTLY_ENV:-PROD}" != "CI" ]] && platform::command_exists zsh; then
   output::empty_line
 fi
 
-output::answer "Linking dot command for all users in \`/usr/local/bin\`"
-ln -f -s "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" /usr/local/bin/dot
-[[ -x "/usr/local/bin/dot" ]] || output::error "\`dot\` command could not be linked"
-output::empty_line
+if ! ${without_link:-false}; then
+  output::answer "Linking dot command for all users in \`/usr/local/bin\`"
+  ln -f -s "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" /usr/local/bin/dot
+  [[ -x "/usr/local/bin/dot" ]] || output::error "\`dot\` command could not be linked"
+  output::empty_line
 
-if ! ${ignore_restoration:-false} && ! ${IGNORE_RESTORATION:-false}; then
-  output::answer "Executing custom restoration scripts"
-  install_scripts_path="${DOTFILES_PATH}/restoration_scripts"
-  if [ -d "$install_scripts_path" ]; then
-    find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
-      sort |
-      while read -r install_script; do
-        #shellcheck disable=SC1090
-        {
-          [[ -x "$install_script" ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"
-        } || {
-          output::error "Install script error in \`$(basename "$install_script")\`"
-        }
-      done
+  if ! ${ignore_restoration:-false} && ! ${IGNORE_RESTORATION:-false}; then
+    output::answer "Executing custom restoration scripts"
+    install_scripts_path="${DOTFILES_PATH}/restoration_scripts"
+    if [ -d "$install_scripts_path" ]; then
+      find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
+        sort |
+        while read -r install_script; do
+          #shellcheck disable=SC1090
+          {
+            [[ -x "$install_script" ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"
+          } || {
+            output::error "Install script error in \`$(basename "$install_script")\`"
+          }
+        done
+    fi
   fi
 fi
 
