Fix 207

diff --git a/scripts/core/install b/scripts/core/install
--- a/scripts/core/install
+++ b/scripts/core/install
@@ -32,18 +32,18 @@ start_sudo() {
 }
 
 stop_sudo() {
-  builtin kill "$SUDO_PID" > /dev/null 2>&1
+  builtin kill "$SUDO_PID" >/dev/null 2>&1
   builtin trap - SIGINT SIGTERM
   command -p sudo -k
 }
 
 has_sudo() {
   [[ "${DOTLY_ENV:-PROD}" == "CI" ]] && return
-  command -p sudo -n -v > /dev/null 2>&1
+  command -p sudo -n -v >/dev/null 2>&1
 }
 
 initilize_sloth_if_necessary() {
-  if ! git::is_in_repo -C "${SLOTH_PATH:-${DOTLY_PATH:-}}" > /dev/null 2>&1; then
+  if ! git::is_in_repo -C "${SLOTH_PATH:-${DOTLY_PATH:-}}" >/dev/null 2>&1; then
     output::answer "Initilizing .Sloth as repository"
     sloth_update::sloth_repository_set_ready 2>&1 | log::file "Initilizing .Sloth as repository" || true
     output::empty_line
@@ -61,7 +61,7 @@ initilize_sloth_if_necessary() {
 ##? Usage:
 ##?    install [-v | --version]
 ##?    install [-h | --help]
-##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-loader] [--ignore-restoration] [--only-git-init-sloth] [--link-prefix <link_prefix>]
+##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-loader] [--ignore-restoration] [--only-git-init-sloth] [--link_prefix <prefix>]
 ##?
 ##? Options:
 ##?    -h --help                Prints this help
@@ -84,8 +84,7 @@ initilize_sloth_if_necessary() {
 #? v3.2.0
 if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docopts" || [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == "-v" || "${1:-}" == "--version" ]]; then
   docs::parse "$@"
-
-  [[ -z "${link_prefix}" ]] && link_prefix="/usr/local"
+  link_prefix="${prefix:-/usr/local}"
 else
   backup=false
   interactive_backup=false
@@ -98,54 +97,54 @@ else
   link_prefix=/usr/local
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
-      --backup)
-        { $interactive_backup || $ignore_backup; } && output::error "Error you can not use \`--backup\` with \`--interactive-backup\` or \`--ignore-backup\`" && exit 4
-        backup=true
-        ;;
-      --interactive-backup)
-        { $backup || $ignore_backup; } && output::error "Error you can not use \`--interactive-backup\` with \`--backup\` or \`--ignore-backup\`" && exit 4
-        interactive_backup=true
-        shift
-        ;;
-      --ignore-backup)
-        { $backup || $interactive_backup; } && output::error "Error you can not use \`--ignore-backup\` with \`--backup\` or \`--interactive-backup\`" && exit 4
-        ignore_backup=true
-        shift
-        ;;
-      --ignore-symlinks)
-        ignore_symlinks=true
-        shift
-        ;;
-      --ignore-loader)
-        ignore_loader=true
-        shift
-        ;;
-      --ignore-restoration)
-        ignore_restoration=true
-        shift
-        ;;
-      --only-git-init-sloth)
-        only_git_init_sloth=true
-        shift
-        ;;
-      --ignore-link)
-        ignore_link=true
-        shift
-        ;;
-      --link-prefix)
-        [[ -z "${2:-}" ]] && output::error "Wrong usage of \`--link-prefix\` option, it should include a second param with the prefix where to link \`dot\` command." && exit 4
-        link_prefix=$2
-        shift 2
-        ;;
-      *)
-        break 2
-        ;;
+    --backup)
+      { $interactive_backup || $ignore_backup; } && output::error "Error you can not use \`--backup\` with \`--interactive-backup\` or \`--ignore-backup\`" && exit 4
+      backup=true
+      ;;
+    --interactive-backup)
+      { $backup || $ignore_backup; } && output::error "Error you can not use \`--interactive-backup\` with \`--backup\` or \`--ignore-backup\`" && exit 4
+      interactive_backup=true
+      shift
+      ;;
+    --ignore-backup)
+      { $backup || $interactive_backup; } && output::error "Error you can not use \`--ignore-backup\` with \`--backup\` or \`--interactive-backup\`" && exit 4
+      ignore_backup=true
+      shift
+      ;;
+    --ignore-symlinks)
+      ignore_symlinks=true
+      shift
+      ;;
+    --ignore-loader)
+      ignore_loader=true
+      shift
+      ;;
+    --ignore-restoration)
+      ignore_restoration=true
+      shift
+      ;;
+    --only-git-init-sloth)
+      only_git_init_sloth=true
+      shift
+      ;;
+    --ignore-link)
+      ignore_link=true
+      shift
+      ;;
+    --link-prefix)
+      [[ -z "${2:-}" ]] && output::error "Wrong usage of \`--link-prefix\` option, it should include a second param with the prefix where to link \`dot\` command." && exit 4
+      link_prefix="${2:-}"
+      shift 2
+      ;;
+    *)
+      break 2
+      ;;
     esac
   done
 fi
 
 if ${only_git_init_sloth:-false}; then
-  if platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1; then
+  if platform::command_exists brew && ! brew list gtrabanco/tools/dot >/dev/null 2>&1; then
     initilize_sloth_if_necessary
   else
     output::answer "Skiping init .Sloth installation as repository because you have used a package manager to install it"
@@ -257,7 +256,7 @@ export SETUP_ZSH_AS_DEFAULT_SHELL
 export ZIM_HOME="${DOTFILES_PATH:-}/shell/zsh/.zimfw"
 export PATH="$HOME/.cargo/bin:$PATH"
 
-if platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1; then
+if platform::command_exists brew && ! brew list gtrabanco/tools/dot >/dev/null 2>&1; then
   # Initilize .Sloth only if necessary
   initilize_sloth_if_necessary
 fi
@@ -347,7 +346,7 @@ fi
 zsh_shell_path="$(command -v zsh || true)"
 output::answer "Trying to setup zsh as the default shell"
 if $SETUP_ZSH_AS_DEFAULT_SHELL && has_sudo; then
-  sudo bash -c "echo '$zsh_shell_path' | tee -a /etc/shells" > /dev/null 2>&1
+  sudo bash -c "echo '$zsh_shell_path' | tee -a /etc/shells" >/dev/null 2>&1
 
   {
     sudo chsh -s "$(command -v zsh)" 2>&1 || output::write "Shell could not be changed to zsh"
@@ -377,7 +376,7 @@ if [[ "${DOTLY_ENV:-PROD}" != "CI" ]] && platform::command_exists zsh; then
   output::answer "Installing completions"
 
   {
-    zsh "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" shell zsh reload_completions > /dev/null 2>&1 &&
+    zsh "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" shell zsh reload_completions >/dev/null 2>&1 &&
       output::solution '✅ ZSH Completions realoaded'
   } || output::error '❌ Error reloading completions. Execute later \`dot shell zsh reload_completions\`'
 
@@ -385,12 +384,12 @@ if [[ "${DOTLY_ENV:-PROD}" != "CI" ]] && platform::command_exists zsh; then
 fi
 
 if
-  platform::command_exists brew && ! brew list gtrabanco/tools/dot > /dev/null 2>&1 ||
+  platform::command_exists brew && ! brew list gtrabanco/tools/dot >/dev/null 2>&1 ||
     ! ${ignore_link:-false}
 then
-  output::answer "Linking dot command for all users in \`/usr/local/bin\`"
-  ln -f -s "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" /usr/local/bin/dot
-  [[ -x "/usr/local/bin/dot" ]] || output::error "\`dot\` command could not be linked"
+  output::answer "Linking dot command for all users in \`${link_prefix}/bin\`"
+  ln -f -s "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" "${link_prefix}/bin/dot"
+  [[ -x "${link_prefix}/dot" ]] || output::error "\`dot\` command could not be linked"
   output::empty_line
 fi
 
