[Fix] unbound variable (#144)
* Fix unbound variable

* Avoid print brew path

* Fixed misspelling in feedback messages

* Create DOTFILES_PATH

* Deleted non needed templates & little formatting in keeped files

* Code formatting

* Improved loader chechks and can be used with standalone installation

* Use defined SLOTH_PATH if it is defined

* Fix misspelling of SLOTH_PATH_VALUE variable

* Fix unbound variable when DOTFILES_PATH is not defined

* Fix unbound variable when DOTFILES_PATH is not defined

* Added all prompts with default values for CI

* Fixed issue with quotation

* Changed to modify .bashrc and .zshrc and not use templating

* Fix copy & paste error

* Improved user feedback

* Fixed brew package name

* Changed user feedback message

* Fixed vars and functions names

* Fix library name

* Added git init in init if necessary function

* Changed initialization of .Sloth as repository

* Changed what to do in CI

* Added DOTFILES_PATH in CI

* Passed DOTFILES_PATH as argument to dot dotfiles create

* Improved feedback if change directory fail

* Debug bash_source

* Debug installer

* Debug SLOTH & DOTLY PATHs

* Added back template files, because we want to keep them in DOTFILES_PATH

* Production cleanup

Co-authored-by: Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>

diff --git a/scripts/core/install b/scripts/core/install
--- a/scripts/core/install
+++ b/scripts/core/install
@@ -4,10 +4,10 @@
 set -euo pipefail
 
 if
-  command -v brew 2> /dev/null &&
-    command brew --prefix gtrabanco/tools/.sloth &> /dev/null
+  command -v brew &> /dev/null &&
+    brew --prefix gtrabanco/tools/dot &> /dev/null
 then
-  SLOTH_PATH="$(command brew --prefix .sloth)"
+  SLOTH_PATH="$(command brew --prefix gtrabanco/tools/dot)"
 else
   SLOTH_PATH="${SLOTH_PATH:-${DOTLY_PATH:-${BASH_SOURCE[0]//\/scripts\/core\/install/}}}"
 fi
@@ -44,9 +44,9 @@ has_sudo() {
 }
 
 initilize_sloth_if_necessary() {
-  if ! git::is_in_repo -C "${SLOTH_PATH:-${DOTLY_PATH:-}}"; then
+  if ! git::is_in_repo -C "${SLOTH_PATH:-${DOTLY_PATH:-}}" &> /dev/null; then
     output::answer "Initilizing .Sloth as repository"
-    sloth_update::sloth_repository_set_ready | log::file "Initilizing .Sloth as repository" || true
+    sloth_update::sloth_repository_set_ready 2>&1 | log::file "Initilizing .Sloth as repository" || true
     output::empty_line
   else
     output::answer ".Sloth is already a repository"
@@ -60,18 +60,25 @@ initilize_sloth_if_necessary() {
 ##? Install dotly and setup dotfiles. By default use a interactive backup (backups are not done for core symlinks).
 ##?
 ##? Usage:
-##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-restoration] [--only-git-init-sloth]
+##?    install [-v | --version]
+##?    install [-h | --help]
+##?    install [[-n | --never-backup] | [-b |--always-backup] | [--ignore-symlinks]] [--ignore-loader] [--ignore-restoration] [--only-git-init-sloth]
 ##?
 ##? Options:
 ##?    -h --help                Prints this help
 ##?    -n --never-backup        Never do a backup of user symlinks without prompt
 ##?    -b --always-backup       Always do a backup of user symlinks without prompt
-##?    -i --interactive-backup  Interactive backup of user symlinks asking for every existing symlink before to be applied (default)
-##?    --ignore-symlinks        Ignore apply symlinks. Useful for very custom installations
+##?    -i --interactive-backup  Interactive backup of user symlinks asking for
+##?                             every existing symlink before to be applied (default).
+##?    --ignore-symlinks        Ignore apply symlinks. Useful for very custom
+##?                             installations.
+##?    --ignore-loader          Ignore the modification of .bashrc, .zshrc and .zshenv
+##?                             (see \`dot core loader --help\` for non default
+##?                             locations of these files)
 ##?    --ignore-restoration     Ignore user restoration scripts
 ##?    --only-git-init-sloth    Executes only the .Sloth initilization if necessary
 ##?
-##? SCRIPT_VERSION "3.1.0"
+##? SCRIPT_VERSION "3.2.0"
 if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docpars"; then
   docs::parse "$@"
 else
@@ -81,6 +88,7 @@ else
   interactive_backup=false
   ignore_backup=false
   ignore_symlinks=false
+  ignore_loader=false
   ignore_restoration=false
   only_git_init_sloth=false
   while [[ $# -gt 0 ]]; do
@@ -113,6 +121,10 @@ else
         ignore_symlinks=true
         shift
         ;;
+      --ignore-loader)
+        ignore_loader=true
+        shift
+        ;;
       --ignore-restoration)
         ignore_restoration=true
         shift
@@ -128,11 +140,9 @@ else
   done
 fi
 
-SCRIPT_NAME="dot core install"
-
 # Print name and version
 if ${version:-false}; then
-  output::write "$SCRIPT_NAME v$(dot::parse_script_version "$(dot::get_full_script_path)")"
+  output::write "${SCRIPT_NAME:-dot core install} v$(docs::parse_script_version "$(dot::get_full_script_path)")"
   exit
 elif ${help:-false}; then
   grep "##?" "$(dot::get_full_script_path)" | cut -c 5-
@@ -142,45 +152,56 @@ elif ${only_git_init_sloth:-false}; then
   exit
 fi
 
+# Default values in CI env
+if [[ "${DOTLY_ENV:-PROD}" == "CI" ]]; then
+  export SETUP_ZSH_AND_BASH_IN_SHELLS=false
+  export IGNORE_APPLY_SYMLINKS=false
+  export SYMLINKS_ARGS=(--ignore-backup)
+  export SETUP_ZSH_AS_DEFAULT_SHELL=false
+  export DOTFILES_PATH="${HOME}/.dotfiles"
+  ignore_loader=true
+  ignore_restoration=true
+  IGNORE_UPDATE_PACKAGES=true
+  DOTFILES_PATH="${HOME}/.dotfiles"
+fi
+
 #### Prompt user all the staff we want to know ####
 #### All questions at the very beginning
-# Setup Zsh and Bash this step is done on both systems but this step that requires elevation with sudo only affects macOS users
+# Adds zsh and bash in /etc/shells (only in macos, in linux is done by the package manager)
 if
-  [[ "${DOTLY_ENV:-PROD}" != "CI" ]] &&
-    platform::is_macos &&
+  platform::is_macos &&
     [[ -z "${SETUP_ZSH_AND_BASH_IN_SHELLS:-}" ]]
 then
   SETUP_ZSH_AND_BASH_IN_SHELLS=false
   if
-    output::yesno "Do you want to setup more modern \`zsh\` & \`bash\` as valid shells in \`/etc/shells\` (require elevation)"
+    output::yesno "Do you want to setup more modern \`zsh\` & \`bash\` as valid shells in \`/etc/shells\` (elevation required; sudo)"
   then
     start_sudo
 
-    sudo -n -v && SETUP_ZSH_AND_BASH_IN_SHELLS=true
-
+    has_sudo && SETUP_ZSH_AND_BASH_IN_SHELLS=true
     ! has_sudo && output::error "It can not be done without elevation, aborting this options (should be done later manually)" && SETUP_ZSH_AND_BASH_IN_SHELLS=false
   fi
 
-# We need to cache sudo to avoid asking for password later and every time
+# If defined the variable, we need to cache the sudo password
 elif
-  [[ "${DOTLY_ENV:-PROD}" != "CI" ]] &&
-    platform::is_macos &&
-    [[ -n "${SETUP_ZSH_AND_BASH_IN_SHELLS:-}" ]]
+  platform::is_macos &&
+    ${SETUP_ZSH_AND_BASH_IN_SHELLS:-false}
 then
   start_sudo
-  ! has_sudo && output::error "It can not be done without elevation, aborting this options (should be done later manually)"
-  SETUP_ZSH_AND_BASH_IN_SHELLS=false
+
+  ! has_sudo &&
+    output::error "It can not be done without elevation, aborting this options (should be done later manually)" &&
+    SETUP_ZSH_AND_BASH_IN_SHELLS=false
 fi
 export SETUP_ZSH_AND_BASH_IN_SHELLS
 
 # Backups
 if
-  { ! ${ignore_symlinks:-false} && ! ${IGNORE_APPLY_SYMLINKS:-false}; } &&
-    [[ -z "${SYMLINKS_ARGS[*]:-}" ]] &&
-    ! { ${ignore_symlinks:-false} || ${IGNORE_APPLY_SYMLINKS:-false}; }
+  ! ${IGNORE_APPLY_SYMLINKS:-false} &&
+    [[ -z "${SYMLINKS_ARGS[*]:-}" ]]
 then
   SYMLINKS_ARGS=(--interactive-backup)
-  if [[ "${DOTLY_ENV:-PROD}" == "CI" ]] || ${never_backup:-}; then
+  if ${never_backup:-}; then
     SYMLINKS_ARGS=(--ignore-backup)
   elif ${always_backup:-}; then
     SYMLINKS_ARGS=(--backup)
@@ -191,30 +212,32 @@ then
     ! $bk && SYMLINKS_ARGS=(--ignore-backup)
   fi
 fi
+export SYMLINKS_ARGS
 
 # ZSH as default Shell
 zsh_shell_path="$(command -v zsh || true)"
 if [[ -z "${SETUP_ZSH_AS_DEFAULT_SHELL:-}" ]]; then
   SETUP_ZSH_AS_DEFAULT_SHELL=false
   if
-    [[ "${DOTLY_ENV:-PROD}" != "CI" ]] &&
-      ! str::contains zsh "$SHELL" &&
+    [[ "$SHELL" == *"zsh"* ]] &&
       platform::command_exists chsh &&
       [[ -x "$zsh_shell_path" ]] &&
       [[ -f "/etc/shells" ]] &&
       ! grep -q "^${zsh_shell_path}$" "/etc/shells"
   then
-    output::yesno "Do you want to setup the zsh \`$zsh_shell_path\` as default shell" && SETUP_ZSH_AS_DEFAULT_SHELL=true
+    output::yesno "Do you want to setup the zsh \`$zsh_shell_path\` as default shell" &&
+      SETUP_ZSH_AS_DEFAULT_SHELL=true
+
     output::answer "This will need a sudo authentication to add it to \`/etc/shells\` file"
+    start_sudo
     if ! has_sudo; then
       output::error "Without sudo authentication this can not be done. You should do this later manually"
       SETUP_ZSH_AS_DEFAULT_SHELL=false
     fi
   fi
 elif
-  [[ -n "${SETUP_ZSH_AS_DEFAULT_SHELL:-}" ]] &&
-    [[ "${DOTLY_ENV:-PROD}" != "CI" ]] &&
-    ! str::contains zsh "$SHELL" &&
+  ${SETUP_ZSH_AS_DEFAULT_SHELL:-false} &&
+    [[ "$SHELL" == *"zsh"* ]] &&
     platform::command_exists chsh &&
     [[ -x "$zsh_shell_path" ]] &&
     [[ -f "/etc/shells" ]] &&
@@ -225,17 +248,7 @@ then
     output::error "\`SETUP_ZSH_AS_DEFAULT_SHELL\` should be aborted because sudo elevation password is not set." &&
     SETUP_ZSH_AS_DEFAULT_SHELL=false
 else
-  if
-    [[ -z "${SETUP_ZSH_AS_DEFAULT_SHELL:-}" ]] ||
-      [[ "${DOTLY_ENV:-PROD}" == "CI" ]] ||
-      ! platform::command_exists chsh ||
-      [[ ! -x "$zsh_shell_path" ]] ||
-      [[ ! -f "/etc/shells" ]] ||
-      grep -q "^${zsh_shell_path}$" "/etc/shells" ||
-      ! has_sudo
-  then
-    SETUP_ZSH_AS_DEFAULT_SHELL=false
-  fi
+  SETUP_ZSH_AS_DEFAULT_SHELL=${SETUP_ZSH_AS_DEFAULT_SHELL:-false}
 fi
 export SETUP_ZSH_AS_DEFAULT_SHELL
 #### End of prompt user all the staff we want to know ####
@@ -267,7 +280,7 @@ fi
 
 if [[ -n "$DOTFILES_PATH" ]]; then
   output::answer "Creating dotfiles structure"
-  "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" dotfiles create | log::file "Creating dotfiles structure" || exit 1
+  "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" dotfiles create "$DOTFILES_PATH" | log::file "Creating dotfiles structure" || exit 1
   output::empty_line
 else
   output::answer "Skipping dotfiles creation"
@@ -279,7 +292,7 @@ fi
 if ! ${ignore_symlinks:-false} && ! ${IGNORE_APPLY_SYMLINKS:-false}; then
   output::answer "Setting up symlinks"
   SYMLINKS_ARGS=(--interactive-backup)
-  if [[ -n "${DOTFILES_PATH:-}" ]]; then
+  if [[ -z "${DOTFILES_PATH:-}" ]]; then
     if "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" symlinks apply "${SYMLINKS_ARGS[@]}" --continue-on-error --after-core 2>&1 | log::file "Applying symlinks"; then
       output::solution "Symlinks applied"
     else
@@ -345,6 +358,12 @@ ln -f -s "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" /usr/local/bin/dot
 [[ -x "/usr/local/bin/dot" ]] || output::error "\`dot\` command could not be linked"
 output::empty_line
 
+if ! ${ignore_loader}; then
+  # Adding .Sloth loader to bashrc and zshrc
+  output::answer "Adding .Sloth loader to .bashrc and .zshrc"
+  "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" core loader --modify
+fi
+
 if ! ${ignore_restoration:-false} && ! ${IGNORE_RESTORATION:-false}; then
   output::answer "Executing custom restoration scripts"
   install_scripts_path="${DOTFILES_PATH}/restoration_scripts"
@@ -387,7 +406,7 @@ else
 fi
 output::empty_line
 
-if [[ "${DOTLY_ENV:-PROD}" != "CI" ]] && ! ${IGNORE_UPDATE_PACKAGES:-false}; then
+if ! ${IGNORE_UPDATE_PACKAGES:-false}; then
   output::answer "Updating all system packages"
   if platform::is_macos; then
     output::empty_line
diff --git a/scripts/dotfiles/create b/scripts/dotfiles/create
--- a/scripts/dotfiles/create
+++ b/scripts/dotfiles/create
@@ -21,22 +21,14 @@ DOTFILES_PATH="${2:-${DOTFILES_PATH:-}}"
 
 [[ -z "$DOTFILES_PATH" ]] && output::error "DOTFILES_PATH not found" && exit 1
 
-dotfiles::apply_templating() {
-  local tpl_files=(
-    "$DOTFILES_PATH/bin/sdot"
-    "$DOTFILES_PATH/shell/bash/.bashrc"
-    "$DOTFILES_PATH/shell/zsh/.zshenv"
-  )
+if ! mkdir -p "$DOTFILES_PATH" 2> /dev/null; then
+  output::error "Could not create \`${DOTFILES_PATH}\`" && exit 1
+fi
 
-  for file in "${tpl_files[@]}"; do
-    templating::replace "$file" --dotfiles-path="${DOTFILES_PATH//$HOME/\$HOME}"
-  done
-}
+if [ ! -d "${DOTFILES_PATH}/shell" ]; then
+  cp -r "${SLOTH_PATH:-${DOTLY_PATH:-}}/dotfiles_template/"* "${DOTFILES_PATH}/"
 
-if [ ! -d "$DOTFILES_PATH/shell" ]; then
-  cp -r "${SLOTH_PATH:-${DOTLY_PATH:-}}/dotfiles_template/"* "$DOTFILES_PATH/"
-
-  dotfiles::apply_templating
+  "${SLOTH_PATH:-${DOTLY_PATH:-}}/bin/dot" core loader --modify
 
   log::success "Done!"
 else
