Changed dot package import to use new libraries, now if you have the package manager and it has a function ::import your packages can be imported

diff --git a/scripts/package/import b/scripts/package/import
--- a/scripts/package/import
+++ b/scripts/package/import
@@ -2,6 +2,7 @@
 
 #shellcheck disable=SC1091
 . "${SLOTH_PATH:-$DOTLY_PATH}/scripts/core/src/_main.sh"
+dot::load_library "package.sh"
 dot::load_library "dump.sh"
 
 ##? Import previously dumped packages from:
@@ -23,89 +24,56 @@ dot::load_library "dump.sh"
 ##?
 docs::parse "$@"
 
-# Define paths for package managers
-# Is defined this way because this enable the user to define a custom path
-BREW_PATH="${BREW_PATH:-$DOTFILES_PATH/os/$(platform::os)/brew}"
-APT_PATH="${APT_PATH:-$DOTFILES_PATH/os/linux/apt}"
-SNAP_PATH="${SNAP_PATH:-$DOTFILES_PATH/os/linux/snap}"
-CARGO_PATH="${CARGO_PATH:-$DOTFILES_PATH/langs/rust/cargo/}"
-PYTHON_PATH="${PYTHON_PATH:-$DOTFILES_PATH/langs/python}"
-NPM_PATH="${NPM_PATH:-$DOTFILES_PATH/langs/js/npm}"
-VOLTA_PATH="${VOLTA_PATH:-$DOTFILES_PATH/langs/js/volta}"
-
-# Define default value for dump file if exist a file with same hostname
-HOMEBREW_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$BREW_PATH")"
-APT_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$APT_PATH")"
-SNAP_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$SNAP_PATH")"
-CARGO_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$CARGO_PATH")"
-PYTHON_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$PYTHON_PATH")"
-NPM_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$NPM_PATH")"
-VOLTA_DUMP_FILE_PATH="$(package::exists_dump_current_machine_file "$VOLTA_PATH")"
-
-if ! ${never_prompt:-false}; then
-  platform::command_exists brew && [[ -z "$HOMEBREW_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$BREW_PATH" "Select ${brew_title:-Brew} file to import" "HOMEBREW_DUMP_FILE_PATH"
-  platform::command_exists apt && [[ -z "$APT_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$APT_PATH" "Select ${apt_title:-APT} file of modules to import" "APT_DUMP_FILE_PATH"
-  platform::command_exists snap && [[ -z "$SNAP_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$SNAP_PATH" "Select ${snap_title:-SNAP} file of modules to import" "SNAP_DUMP_FILE_PATH"
-  platform::command_exists cargo && [[ -z "$CARGO_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$CARGO_PATH" "Select ${cargo_title:-Cargo} file to import" "CARGO_DUMP_FILE_PATH"
-  platform::command_exists pip3 && [[ -z "$PYTHON_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$PYTHON_PATH" "Select ${pip_title:-Python} requirements file to import" "PYTHON_DUMP_FILE_PATH"
-  platform::command_exists volta && [[ -z "$VOLTA_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$VOLTA_PATH" "Select ${volta_title:-volta} file to import" "VOLTA_DUMP_FILE_PATH"
-  platform::command_exists npm && [[ -z "$NPM_DUMP_FILE_PATH" ]] || ${prompt:-false} && package::which_file "$NPM_PATH" "Select ${npm_title:-NPM} file of modules to import" "NPM_DUMP_FILE_PATH"
-fi
 
 output::write "🎩 Let's import your packages (this could take a while)" && output::empty_line
 
-{
-  platform::command_exists brew && [[ -n "$HOMEBREW_DUMP_FILE_PATH" ]] &&
-    output::header "Importing Brew apps from $HOMEBREW_DUMP_FILE_PATH" &&
-    package::brew_import &&
-    output::empty_line
-} ||
-  output::answer "Ignoring Brew"
+for package_manager in $(package::get_available_package_managers); do
+  # Reset
+  file_path=""
+  directory_file_path=""
 
-{
-  platform::command_exists apt-mark &&
-    output::header "Importing Apt apps from $APT_DUMP_FILE_PATH" &&
-    package::apt_import &&
-    output::empty_line
-} ||
-  output::answer "Ignoring APT"
+  # Setting variables
+  file_path="$(dump::file_path "$package_manager" "$(hostname -s)")"
+  directory_file_path="$(dirname "$file_path")"
 
-{
-  platform::command_exists snap &&
-    output::header "Importing Snap apps from $SNAP_DUMP_FILE_PATH" &&
-    package::snap_import &&
-    output::empty_line
-} ||
-  output::answer "Ignoring SNAP"
+  # Continue if is npm and volta is isntalled
+  if
+    [[ $package_manager == "npm" ]] &&
+    package::get_available_package_managers | grep -q "^volta$" ||
+    ! package::command_exists "$package_manager" "dump"
+  then
+    continue
+  fi
 
-{
-  platform::command_exists cargo &&
-    output::header "Importing Cargo apps from $CARGO_DUMP_FILE_PATH" &&
-    package::cargo_import &&
-    output::empty_line
-} ||
-  output::answer "Ignoring Cargo"
+  # If always prompt or file does not exists and no never prompt ask fot the importing file
+  {
+    ${prompt:-false} ||
+    [[ ! -f "$file_path" ]] &&
+    ! ${never_prompt:-false} &&
+    file_path=""
+  } && package::which_file "$directory_file_path" "Select $(eval echo "\$${package_manager}_title") file to import" "file_path"
 
-{
-  platform::command_exists pip3 && [[ -n "$PYTHON_DUMP_FILE_PATH" ]] &&
+
+  output::empty_line
+  output::h2 "🚀 Importing $(eval echo "\$${package_manager}_title") apps"
+
+  [[ -z "$file_path" ]] &&
+    output::answer "Ignoring $(eval echo "\$${package_manager}_title") import" &&
     output::empty_line &&
-    output::header "Importing Python apps from $PYTHON_DUMP_FILE_PATH" &&
-    package::python_import
-} ||
-  output::empty_line && output::answer "Ignoring the import of python packages"
-
-if platform::command_exists volta && [[ -n "$VOLTA_DUMP_FILE_PATH" ]]; then
-  output::empty_line &&
-    output::header "Importing Volta apps from $VOLTA_DUMP_FILE_PATH" && output::empty_line &&
-    package::volta_import "$VOLTA_DUMP_FILE_PATH"
-elif platform::command_exists npm && [[ -n "$NPM_DUMP_FILE_PATH" ]]; then
-  output::empty_line &&
-    output::header "Importing NPM apps from $NPM_DUMP_FILE_PATH" && output::empty_line &&
-    package::npm_import "$NPM_DUMP_FILE_PATH"
-else
-  output::empty_line &&
-    output::answer "Ignoring the import of volta or npm packages"
-fi
+    continue
+  
+  {
+    [[ -f "$file_path" ]] &&
+    package::command_exists "$package_manager" "import" &&
+    package::load_manager "$package_manager" &&
+    package::command "$package_manager" "import" "$file_path" &&
+    output::answer "$(eval echo "\$${package_manager}_title") apps importing from \`${file_path}\`" &&
+    output::empty_line
+  } || {
+    output::error "Error while try to import $(eval echo "\$${package_manager}_title") apps from \`${file_path}\`" &&
+    output::empty_line
+  }
+done
 
 output::empty_line
 output::solution 'All packages imported'
