Added script to determine which package manager was used to install it

diff --git a/scripts/package/which b/scripts/package/which
--- a/scripts/package/which
+++ b/scripts/package/which
@@ -7,12 +7,32 @@ set -euo pipefail
 #shellcheck disable=SC1091
 . "${DOTLY_PATH:-$SLOTH_PATH}/scripts/core/src/_main.sh"
 
+which_package_output() {
+  local package_manager package_name
+  package_name="${1:-}"
+  [[ -z "$package_name" ]] && return
+  package_manager="$( package::which_package_manager "$package_name" || true )"
+  if [[ -z "$package_manager" ]] && platform::command_exists "$package_name"; then
+    output::error "Command named \`${package_name}\` was detected but could not be determined which package manager was used to install it"
+    return 1
+  elif [[ -z "$package_manager" ]]; then
+    output::error "Package named \`${package_name}\` was not installed with any package manager"
+    return 1
+  else
+    output::solution "Package named \`${package_name}\` was installed with \`$package_manager\`"
+  fi
+}
+
 ##? Gives user information about which package manager have been used to install a package
 ##?
 ##?
 ##? Usage:
 ##?   which [-h | --help]
 ##?   which [-v | --version]
+##?   which <packages_names>...
+##?
+##? Arguments:
+##?   package_name  The package that must check from which package manager is installed with. You can provide as much packages you want
 ##?
 ##? Options:
 ##?   -h --help     Show this help
@@ -21,22 +41,23 @@ set -euo pipefail
 ##? Author:
 ##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
 ##?
+##? SCRIPT_VERSION "1.0.0"
 docs::parse "$@"
 
-SCRIPT_NAME="dot package which"
-SCRIPT_VERSION="1.0.0"
-
-# Print name and version
-if ${version:-}; then
-  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
-  exit
+if [[ -z "${packages_names[*]:-}" ]]; then
+  output::error "Wrong number of params, seeing \`${SCRIPT_NAME:-} --help\`:"
+  output::empty_line
+  docs::parse "--help"
+  exit 1
 fi
 
-# Here begin your script
+output_code=0
+if [[ ${#packages_names[@]} -eq 1 ]]; then
+  which_package_output "${packages_names[*]}" || output_code=1
+else
+  for package_name in "${packages_names[@]}"; do
+    which_package_output "$package_name" || output_code=1
+  done
+fi
 
-case ${1-} in
-  # Any subcommand should be here
-  *)
-    exit 1
-    ;;
-esac
+exit $output_code
