Linting

diff --git a/scripts/mac/defaults b/scripts/mac/defaults
--- a/scripts/mac/defaults
+++ b/scripts/mac/defaults
@@ -23,57 +23,57 @@ DOTLY_MACOS_SETTINGS_PATH=${DOTLY_MACOS_SETTINGS_PATH:-"${DOTFILES_PATH}/os/mac/
 docs::parse "$@"
 
 case $1 in
-"view_changed")
-  current_defaults_path="$(mktemp)"
-  defaults read >"$current_defaults_path"
+  "view_changed")
+    current_defaults_path="$(mktemp)"
+    defaults read > "$current_defaults_path"
 
-  git diff -w --no-index "$DOTLY_PATH/scripts/mac/utils/macos-11.0-defaults" "$current_defaults_path" | delta --side-by-side
-  ;;
-"export")
-  if [[ -z "${export_name:-}" ]] || { ${prompt:-false} && ! ${never_prompt:-false}; }; then
-    output::question_default "Write the subfolder do you want to export" "$(hostname -s)" "export_name"
-  elif $never_prompt; then
-    export_name="$(hostname -s)"
-  fi
+    git diff -w --no-index "$DOTLY_PATH/scripts/mac/utils/macos-11.0-defaults" "$current_defaults_path" | delta --side-by-side
+    ;;
+  "export")
+    if [[ -z "${export_name:-}" ]] || { ${prompt:-false} && ! ${never_prompt:-false}; }; then
+      output::question_default "Write the subfolder do you want to export" "$(hostname -s)" "export_name"
+    elif $never_prompt; then
+      export_name="$(hostname -s)"
+    fi
 
-  export_plist_path="${DOTLY_MACOS_SETTINGS_PATH}/${export_name:-}"
-  if [[ -n "${export_name}" ]] && { [[ -d "$export_plist_path" ]] || mkdir -p "$export_plist_path"; }; then
-    defaults domains | tr ", " "\n" | sed -r '/^\s*$/d' | xargs -I_ defaults export _ "$export_plist_path/_.plist"
-    output::solution "Defaults exported to: ${export_plist_path//$DOTFILES_PATH/\$DOTFILES_PATH}"
-  else
-    output::error "Defaults could not be exported"
-  fi
-  ;;
-"import")
-  if [[ -z "${import_name:-}" ]] || { ${prompt:-false} && ! ${never_prompt:-false}; }; then
-    import_name=$(find "$DOTLY_MACOS_SETTINGS_PATH"/* -not -iname ".*" -not -path "$DOTLY_MACOS_SETTINGS_PATH" -type d -print0 | xargs -0 -I _ basename _ | fzf --header "Select settings name to import")
-  elif ${never_prompt:-false}; then
-    import_name="$(hostname -s)"
-  fi
+    export_plist_path="${DOTLY_MACOS_SETTINGS_PATH}/${export_name:-}"
+    if [[ -n "${export_name}" ]] && { [[ -d "$export_plist_path" ]] || mkdir -p "$export_plist_path"; }; then
+      defaults domains | tr ", " "\n" | sed -r '/^\s*$/d' | xargs -I_ defaults export _ "$export_plist_path/_.plist"
+      output::solution "Defaults exported to: ${export_plist_path//$DOTFILES_PATH/\$DOTFILES_PATH}"
+    else
+      output::error "Defaults could not be exported"
+    fi
+    ;;
+  "import")
+    if [[ -z "${import_name:-}" ]] || { ${prompt:-false} && ! ${never_prompt:-false}; }; then
+      import_name=$(find "$DOTLY_MACOS_SETTINGS_PATH"/* -not -iname ".*" -not -path "$DOTLY_MACOS_SETTINGS_PATH" -type d -print0 | xargs -0 -I _ basename _ | fzf --header "Select settings name to import")
+    elif ${never_prompt:-false}; then
+      import_name="$(hostname -s)"
+    fi
 
-  import_plist_path="${DOTLY_MACOS_SETTINGS_PATH}/${import_name:-}"
+    import_plist_path="${DOTLY_MACOS_SETTINGS_PATH}/${import_name:-}"
 
-  if [[ -z "${import_name:-}" ]] || [[ ! -d "$import_plist_path" ]]; then
-    output::error "No import defaults name selected or settings name does not exits."
-    exit
-  fi
+    if [[ -z "${import_name:-}" ]] || [[ ! -d "$import_plist_path" ]]; then
+      output::error "No import defaults name selected or settings name does not exits."
+      exit
+    fi
 
-  killall System\ Preferences >/dev/null 2>&1
-  sudo -v
+    killall System\ Preferences > /dev/null 2>&1
+    sudo -v
 
-  if [[ -d "$import_plist_path" ]]; then
-    for plist in "${import_plist_path}"/*.plist; do
-      defaults import "$(basename ${plist%.*})" "$plist"
-    done
-    output::solution "Defaults '$import_name' imported."
-  fi
+    if [[ -d "$import_plist_path" ]]; then
+      for plist in "${import_plist_path}"/*.plist; do
+        defaults import "$(basename ${plist%.*})" "$plist"
+      done
+      output::solution "Defaults '$import_name' imported."
+    fi
 
-  killall Dock
-  killall Finder
-  output::answer "A Reboot is suggested"
-  output::yesno "Do you want to reboot now" && sudo reboot
-  ;;
-*)
-  exit 1
-  ;;
+    killall Dock
+    killall Finder
+    output::answer "A Reboot is suggested"
+    output::yesno "Do you want to reboot now" && sudo reboot
+    ;;
+  *)
+    exit 1
+    ;;
 esac
